export const AnalyticsStyle = {
    topHeader: {
      color: "#0E112A",
      fontSize: "29px",
      fontWeight: 700,
      lineHeight: "37px",
      marginTop: "30px",
      marginLeft: "26px",
    },
    boxStyle: {
      boxShadow: "0px 0px 6px #E2E2E2",
      borderRadius: "8px",
      backgroundColor: "#fff",
    },
    durationContainer: {
      display: "flex",
      flexDirection: "row",
      margin: "20px 5%",
      width: "90%",
      justifyContent: "space-between",
    },
    boxContainer: {
      margin: "5% auto 0 auto",
      width: "90%",
      borderRadius: "12px",
      padding: "15px",
      display: "flex",
      justifyContent: "space-between",
      backgroundColor: "#fff",
      boxShadow: "0px 1px 4px rgba(0,0,0,0.1)",
    },
    tab: {
      width: "22%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      height: "30px",
      borderRadius: "9px",
      cursor: "pointer",
    },
    activeTab: {
      backgroundColor: "#FFF",
    },
    NonActiveDuration: {
      color: "#898989",
      fontSize: "11px",
      fontWeight: 700,
      lineHeight: "16px",
      letterSpacing: "0.22px",
    },
    boxContainerTitle: {
      color: "#898989",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16px",
      letterSpacing: "0.244px",
    },
    boxContainerSubTitle: {
      color: "#000",
      fontSize: "15px",
      fontWeight: 600,
      lineHeight: "18px",
      marginTop: "5px",
    },
    smallBox: {
      width: "47.5%",
      margin: 0,
    },
    date: {
      color: "#898989",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16px",
      letterSpacing: "0.244px",
    },
    hourHeaderContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "baseline",
    },
    hourNumber: {
      color: "#000",
      fontSize: "29px",
      fontWeight: 600,
      lineHeight: "37px",
    },
    hourText: {
      color: "#000",
      fontSize: "24px",
      fontWeight: 500,
      lineHeight: "37px",
    },
    hourHeaderSubText: {
      color: "#898989",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "17px",
    },
    upDownIcon: {
      color: "rgba(206, 0, 62, 0.69)",
      fontWeight: 600,
      fontSize: "12px",
    },
    upIcon: {
      color: "rgba(16, 206, 0, 0.69)",
      fontWeight: 600,
      fontSize: "12px",
    },
    upDownIconMargin: {
      fontSize: "16px",
      marginLeft: "-4px",
    },
    arrowIcon: {
      fontSize: "18px",
      color: "rgba(0,0,0,0.5)",
      fontWeight: 400,
    },
  };
  